---
name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Metadata
        uses: damacus/check-chef-metadata-action
        with:
          maintainer_email: bots@acme.org
          maintainer: "xorima"
